#! /bin/csh
set w=`whoami`.imk
set OLD=/tmp/$w/OLD
if ( -d $OLD ) then
else
   mkdir -p $OLD
endif
mv minitoc.sty mtcoff.sty mtcmess.sty minitoc.ist fminitoc.dtx fminitoc.ist minitoc.pre franc.sty frbib.sty frnew.sty $OLD
mv mypatches.sty boldsc.sty $OLD
mv mtcpatchmem.sty $OLD
mv *.mld $OLD
mv *.mlo $OLD
mv *.lan $OLD
mv mtc-add.bib $OLD
foreach i ( \
   mtc-2c mtc-2nd mtc-add mtc-ads mtc-amm mtc-apx mtc-art \
   mtc-bk mtc-bo mtc-ch0 mtc-cri mtc-fo1 mtc-fo2 mtc-gap \
   mtc-hi1 mtc-hi2 mtc-hia mtc-hir mtc-hop mtc-liv \
   mtc-mem mtc-mm1 mtc-mu mtc-sbf mtc-scr mtc-syn \
   mtc-tbi mtc-tlc mtc-tlo mtc-tsf \
)
   foreach j ( tex pdf )
   mv $i.$j $OLD
   end
end
latex minitoc.ins
cp minitoc.log minitoc.log1
