#!/bin/sh
# In this script $1 stands for the first argument passed to the
# script.  The three lines preceding EOF are passed as standard
# input to the program called on the first line.  For example,
# typing
#
# testfont foo
#
# to the UNIX shell has the same effect as typing
#
# tex grtestfont                %this line is read by the shell
# foo                           %these three lines are read by TeX
# \bigtest
# \end
# mv grtestfont.dvi foo.dvi     %this is again read by the shell
#
# mv means move, or rename.
#
     
tex grtestfont << EOF
$1
\bigtest
\end
EOF
mv grtestfont.dvi $1.dvi
